name: swift_qrcodejs
options:
  bundleIdPrefix: io.github.ApolloZhu
  deploymentTarget:
    iOS: 9.0
    macOS: '10.9'
    watchOS: 2.0
    tvOS: 9.0
  indentWidth: 4
  tabWidth: 4
  usesTabs: false
targets:
  QRCodeSwiftCLI:
    type: tool
    platform: macOS
    deploymentTarget: "10.9"
    sources: [Example/main.swift]
    settings:
      CODE_SIGN_IDENTITY: "-"
    dependencies:
      - target: QRCodeSwift_macOS
  QRCodeSwift:
    platform: [macOS, iOS, tvOS, watchOS]
    settings:
      SWIFT_VERSION: 5.0
      APPLICATION_EXTENSION_API_ONLY: 'YES'
      PRODUCT_BUNDLE_IDENTIFIER: "io.github.ApolloZhu.QRCodeSwift"
      EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200: 'arm64 arm64e armv7 armv7s armv6 armv8'
      EXCLUDED_ARCHS: '$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))'
    scheme: {}
    sources: [Sources]
    type: framework
