name: Carthage

on: [push, pull_request]

jobs:
  all:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./carthage.sh build --no-skip-current --verbose
