name: Documentation

on:
  release:
    types: [ published ]

jobs:
  pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Pod CocoaPods Spec
        run: pod spec lint
      - name: Publish to CocoaPods Trunk
        run: pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
  docs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Jazzy
        run: sudo gem install jazzy
      - name: Generate Documentation
        run: jazzy --clean --author ${{ github.repository_owner }} --author_url https://${{ github.repository_owner }}.github.io --github_url https://github.com/${{ github.repository }} --github-file-prefix https://github.com/${{ github.repository }}/tree/${{ github.event.release.tag_name }} --module-version ${{ github.event.release.tag_name }} --swift-build-tool spm --module swift_qrcodejs --root-url https://${{ github.repository_owner }}.github.io/swift_qrcodejs/ --dash_url https://${{ github.repository_owner }}.github.io/swift_qrcodejs/docsets/swift_qrcodejs.xml
      - name: Publish
        run: |
          set -eo pipefail
          cd docs
          git init
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout --orphan gh-pages
          git add --all
          git commit --allow-empty -m "Document ${{ github.event.release.tag_name }}"
          git push origin gh-pages --force
