name: Release

on:
  release:
    types: [ published ]

jobs:
  pod:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to CocoaPods Trunk
        run: pod trunk push
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
