name: Swift Package Manager

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage --parallel
    - name: Prepare Codecov
      run: xcrun llvm-cov export -format="lcov" .build/debug/swift_qrcodejsPackageTests.xctest/Contents/MacOS/swift_qrcodejsPackageTests -instr-profile .build/debug/codecov/default.profdata > codecov.lcov
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: codecov.lcov

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: [latest, 5.3, 5.2, 5.1, '5.0']
    container:
      image: swift:${{ matrix.swift-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v --enable-test-discovery || swift test -v
